import {identity,approved,db,settings,payload,fail,AppError,todayJST,saveRecords} from '@/lib/league';
export const dynamic='force-dynamic';
const redirectUri='https://www.healthplanet.jp/success.html';
async function cryptKey(){return crypto.subtle.importKey('raw',await crypto.subtle.digest('SHA-256',new TextEncoder().encode(settings().TOKEN_ENCRYPTION_KEY!)),{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function encrypt(value:string){const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},await cryptKey(),new TextEncoder().encode(value));return JSON.stringify({iv:Array.from(iv),data:Array.from(new Uint8Array(data))})}
async function decrypt(value:string){const {iv,data}=JSON.parse(value);return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:new Uint8Array(iv)},await cryptKey(),new Uint8Array(data)))}
function configured(){const c=settings();if(!c.HP_CLIENT_ID||!c.HP_CLIENT_SECRET||!c.TOKEN_ENCRYPTION_KEY)throw new AppError('HealthPlanetの開発者キーが未設定です。現在は手入力・CSVをご利用ください。',503);return c;}
export async function GET(){try{const u=await identity();await approved(u.userId);const c=configured();const params=new URLSearchParams({client_id:c.HP_CLIENT_ID!,redirect_uri:redirectUri,scope:'pedometer',response_type:'code'});return Response.json({url:'https://www.healthplanet.jp/oauth/auth?'+params},{headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e)}}
export async function POST(request:Request){try{const u=await identity();await approved(u.userId);const p=await payload(request),c=configured();if(p.action==='disconnect'){await db().prepare('DELETE FROM connections WHERE user_id=?').bind(u.userId).run();return Response.json({ok:true});}if(p.action==='connect'){if(typeof p.code!=='string'||p.code.length<5||p.code.length>1024)throw new AppError('許可画面で発行された認証コードを入力してください。');const result=await fetch('https://www.healthplanet.jp/oauth/token',{method:'POST',body:new URLSearchParams({client_id:c.HP_CLIENT_ID!,client_secret:c.HP_CLIENT_SECRET!,redirect_uri:redirectUri,code:p.code.trim(),grant_type:'authorization_code'}),signal:AbortSignal.timeout(15000)});const token=await result.json() as {access_token?:string;expires_in?:number};if(!result.ok||!token.access_token)throw new AppError('認証できませんでした。HealthPlanetで再度許可して、10分以内にコードを入力してください。');await db().prepare('INSERT INTO connections(user_id,token,expires_at,last_sync) VALUES(?,?,?,0) ON CONFLICT(user_id) DO UPDATE SET token=excluded.token,expires_at=excluded.expires_at,last_sync=0').bind(u.userId,await encrypt(token.access_token),Date.now()+Math.min(Number(token.expires_in)||86400,90*86400)*1000).run();return Response.json({ok:true});}
if(p.action==='sync'){const row=await db().prepare('SELECT * FROM connections WHERE user_id=?').bind(u.userId).first<{token:string;expires_at:number;last_sync:number}>();if(!row||row.expires_at<Date.now())throw new AppError('HealthPlanetを再接続してください。',401);const now=Date.now();const lease=await db().prepare('UPDATE connections SET last_sync=? WHERE user_id=? AND last_sync<?').bind(now,u.userId,now-60000).run();if(!lease.meta.changes)throw new AppError('同期は1分に1回です。少し待ってからお試しください。',429);const today=todayJST(),from=today.slice(0,7).replace('-','')+'01000000',to=today.replaceAll('-','')+'235959';const result=await fetch('https://www.healthplanet.jp/status/pedometer.json',{method:'POST',body:new URLSearchParams({access_token:await decrypt(row.token),tag:'6331',date:'1',from,to}),signal:AbortSignal.timeout(15000)});const data=await result.json() as {data?:{date:string;keydata:string;model:string;tag:string}[]};if(!result.ok||!Array.isArray(data.data))throw new AppError('歩数を取得できませんでした。HealthPlanetの接続を確認してください。');const days=new Map<string,{date:string;steps:number;source:string}>();for(const r of data.data){if(String(r.tag)!=='6331'||!/^\d{12,14}$/.test(r.date))continue;const date=r.date.slice(0,4)+'-'+r.date.slice(4,6)+'-'+r.date.slice(6,8),steps=Number(r.keydata);if(date.slice(0,7)!==today.slice(0,7)||date>today||!Number.isInteger(steps)||steps<0||steps>100000)continue;const source=r.model==='00000000'?'healthplanet-manual':'device';const old=days.get(date);if(!old||steps>old.steps)days.set(date,{date,steps,source});}if(days.size)await saveRecords(u.userId,[...days.values()],'device');return Response.json({ok:true,count:days.size});}throw new AppError('操作を確認してください。')}catch(e){return fail(e)}}
