import {getChatGPTUser} from '@/app/chatgpt-auth';
import {AppError,approved,db,fail,identity,isAdmin,payload,todayJST} from '@/lib/league';
import {PREFECTURES} from '@/lib/competition';
export const dynamic='force-dynamic';
const text=(v:unknown,max:number,label:string,optional=false)=>{if(optional&&(v===null||v===undefined||v===''))return '';if(typeof v!=='string'||!v.trim()||v.trim().length>max)throw new AppError(`${label}を確認してください。`);return v.trim()};
const url=(v:unknown)=>{if(v===null||v===undefined||v==='')return '';let u:URL;try{u=new URL(String(v))}catch{throw new AppError('詳細URLを確認してください。')}if(!['https:','http:'].includes(u.protocol)||u.username||u.password||u.href.length>500)throw new AppError('詳細URLを確認してください。');return u.href};
export async function GET(){try{const u=await getChatGPTUser();if(!u)return Response.json({posts:[],sessions:[],pulse:{logs:0,cheers:0,people:0}});const administrator=await isAdmin(u.userId);if(!administrator)await approved(u.userId);const database=db();const [posts,sessions,pulse]=await Promise.all([
 database.prepare(`SELECT p.*,m.name,m.company,m.role,(SELECT COUNT(*) FROM post_reactions r WHERE r.post_id=p.id) AS cheers,EXISTS(SELECT 1 FROM post_reactions r WHERE r.post_id=p.id AND r.user_id=?) AS cheered FROM activity_posts p JOIN members m ON m.id=p.user_id WHERE p.hidden=0 ORDER BY p.created_at DESC LIMIT 60`).bind(u.userId).all(),
 database.prepare(`SELECT s.*,(SELECT COUNT(*) FROM session_interests i WHERE i.session_id=s.id) AS interest_count,EXISTS(SELECT 1 FROM session_interests i WHERE i.session_id=s.id AND i.user_id=?) AS interested FROM community_sessions s WHERE s.status='published' OR ?=1 ORDER BY s.starts_at ASC LIMIT 30`).bind(u.userId,administrator?1:0).all(),
 database.prepare(`SELECT (SELECT COUNT(*) FROM activity_posts WHERE hidden=0) AS logs,(SELECT COUNT(*) FROM post_reactions r JOIN activity_posts p ON p.id=r.post_id WHERE p.hidden=0) AS cheers,(SELECT COUNT(DISTINCT user_id) FROM activity_posts WHERE hidden=0) AS people`).first()
]);return Response.json({posts:posts.results,sessions:sessions.results,pulse},{headers:{'Cache-Control':'no-store'}})}catch(e){return fail(e)}}
export async function POST(request:Request){try{const u=await identity(),p=await payload(request),database=db();if(p.action==='post'){await approved(u.userId);const day=text(p.activity_date,10,'日付');if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||day>todayJST()||day<todayJST().slice(0,7)+'-01')throw new AppError('当月の今日までの日付を指定してください。');const steps=Number(p.steps);if(!Number.isInteger(steps)||steps<0||steps>100000)throw new AppError('歩数は0〜100,000の整数で入力してください。');const prefecture=text(p.prefecture,20,'都道府県',true);if(prefecture&&!PREFECTURES.includes(prefecture))throw new AppError('都道府県を確認してください。');await database.prepare('INSERT INTO activity_posts(id,user_id,activity_date,title,body,place_name,prefecture,steps,created_at,hidden) VALUES(?,?,?,?,?,?,?,?,?,0)').bind(crypto.randomUUID(),u.userId,day,text(p.title,80,'タイトル'),text(p.body,600,'本文'),text(p.place_name,100,'場所',true)||null,prefecture||null,steps,new Date().toISOString()).run();return Response.json({ok:true})}
 if(p.action==='cheer'){await approved(u.userId);const id=text(p.id,100,'投稿');const found=await database.prepare('SELECT id,user_id FROM activity_posts WHERE id=? AND hidden=0').bind(id).first<{id:string;user_id:string}>();if(!found)throw new AppError('投稿が見つかりません。',404);if(found.user_id===u.userId)throw new AppError('自分の投稿には送れません。');const existing=await database.prepare('SELECT post_id FROM post_reactions WHERE post_id=? AND user_id=?').bind(id,u.userId).first();if(existing)await database.prepare('DELETE FROM post_reactions WHERE post_id=? AND user_id=?').bind(id,u.userId).run();else await database.prepare('INSERT INTO post_reactions(post_id,user_id,created_at) VALUES(?,?,?)').bind(id,u.userId,new Date().toISOString()).run();return Response.json({ok:true})}
 if(p.action==='interest'){await approved(u.userId);const id=text(p.id,100,'企画');const found=await database.prepare("SELECT id FROM community_sessions WHERE id=? AND status='published'").bind(id).first();if(!found)throw new AppError('企画が見つかりません。',404);const existing=await database.prepare('SELECT session_id FROM session_interests WHERE session_id=? AND user_id=?').bind(id,u.userId).first();if(existing)await database.prepare('DELETE FROM session_interests WHERE session_id=? AND user_id=?').bind(id,u.userId).run();else await database.prepare('INSERT INTO session_interests(session_id,user_id,created_at) VALUES(?,?,?)').bind(id,u.userId,new Date().toISOString()).run();return Response.json({ok:true})}
 if(!await isAdmin(u.userId))throw new AppError('運営者のみ操作できます。',403);
 if(p.action==='hide'){await database.prepare('UPDATE activity_posts SET hidden=1 WHERE id=?').bind(text(p.id,100,'投稿')).run();return Response.json({ok:true})}
 if(p.action==='publish_session'){const result=await database.prepare("UPDATE community_sessions SET status='published' WHERE id=? AND status='draft'").bind(text(p.id,100,'企画')).run();if(!result.meta.changes)throw new AppError('下書きが見つかりません。');return Response.json({ok:true})}
 if(p.action==='create_session'){if(!['walk','recovery','pop_up','drop'].includes(p.kind))throw new AppError('企画の種類を確認してください。');const prefecture=text(p.prefecture,20,'都道府県');if(!PREFECTURES.includes(prefecture)||prefecture==='回答しない')throw new AppError('都道府県を確認してください。');const starts=text(p.starts_at,40,'開催日時'),time=Date.parse(starts);if(!Number.isFinite(time))throw new AppError('開催日時を確認してください。');const capacity=Number(p.capacity);if(!Number.isInteger(capacity)||capacity<1||capacity>10000)throw new AppError('定員を確認してください。');await database.prepare("INSERT INTO community_sessions(id,kind,title,host,description,prefecture,city,starts_at,capacity,link,status,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,'draft',?,?)").bind(crypto.randomUUID(),p.kind,text(p.title,100,'企画名'),text(p.host,100,'主催・協賛'),text(p.description,800,'内容'),prefecture,text(p.city,100,'会場'),new Date(time).toISOString(),capacity,url(p.link)||null,u.userId,new Date().toISOString()).run();return Response.json({ok:true})}
 throw new AppError('操作を確認してください。')}catch(e){return fail(e)}}
