'use client';
import {useCallback,useEffect,useState} from 'react';
import {ArrowUpRight,CalendarDays,Check,Heart,MapPin,MessageCircle,Plus,Share2,Shirt,Users} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {PREFECTURES} from '@/lib/competition';

type Post={id:string;user_id:string;name:string;company:string;role:string;activity_date:string;title:string;body:string;place_name:string|null;prefecture:string|null;steps:number;created_at:string;cheers:number;cheered:number;hidden:number};
type Session={id:string;kind:string;title:string;host:string;description:string;prefecture:string;city:string;starts_at:string;capacity:number;link:string|null;status:string;interest_count:number;interested:number};
type CommunityData={posts:Post[];sessions:Session[];pulse:{logs:number;cheers:number;people:number};error?:string};
const empty:CommunityData={posts:[],sessions:[],pulse:{logs:0,cheers:0,people:0}};
const kinds:Record<string,{label:string;icon:typeof Users}>={walk:{label:'WALK SESSION',icon:Users},recovery:{label:'RECOVERY SPOT',icon:Heart},pop_up:{label:'POP-UP',icon:Shirt},drop:{label:'APPAREL DROP',icon:Shirt}};
const dateJST=()=>new Date(Date.now()+9*3600000).toISOString().slice(0,10);

export default function CommunityPanel({authenticated,approved,admin,userId}:{authenticated:boolean;approved:boolean;admin:boolean;userId?:string}){
 const [data,setData]=useState<CommunityData>(empty),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dialog,setDialog]=useState('');
 const load=useCallback(async()=>{if(!authenticated){setLoading(false);return}setLoading(true);try{const r=await fetch('/api/community');const d=await r.json() as CommunityData;if(!r.ok)throw new Error(d.error);setData(d);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[authenticated]);
 useEffect(()=>{void load()},[load]);
 async function action(body:unknown,message:string){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/community',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);await load();setNotice(message);return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
 function share(post:Post){const text=`${post.title}｜${post.steps.toLocaleString('ja-JP')}歩 #AISTRIDE`;window.open(`https://x.com/intent/post?text=${encodeURIComponent(text)}&url=${encodeURIComponent(window.location.origin)}`,'_blank','noopener,noreferrer')}
 return <div className="community-panel">
  <section className="loop-banner"><div><span className="eyebrow">COMMUNITY LOOP</span><h3>歩く。残す。つながる。次が生まれる。</h3></div><ol><li><b>01</b> WALK</li><li><b>02</b> LOG</li><li><b>03</b> CHEER</li><li><b>04</b> MEET / REWARD</li></ol></section>
  <div className="community-stats"><div><span>STRIDE LOG</span><strong>{data.pulse.logs}</strong></div><div><span>NICE STRIDE</span><strong>{data.pulse.cheers}</strong></div><div><span>参加した仲間</span><strong>{data.pulse.people}</strong></div><p>投稿10 PULSE・受け取った応援1 PULSE。コミュニティ貢献の表示に使い、歩数賞品の判定には使いません。</p></div>
  {error&&<p className="error-box" role="alert">{error}</p>}{notice&&<p className="success-box" role="status"><Check size={16}/>{notice}</p>}
  <div className="community-grid"><section><div className="community-head"><div><span className="eyebrow">FIELD NOTES</span><h3>みんなのSTRIDE LOG</h3></div><Button onClick={()=>approved?setDialog('post'):setDialog('gate')}><Plus size={16}/>歩いた記録を投稿</Button></div>
   {!authenticated?<Gate text="X連携エントリー後、承認された仲間の記録を読めます。"/>:loading?<div className="empty">コミュニティを読み込み中…</div>:!data.posts.length?<div className="community-empty"><MessageCircle/><h4>最初の一歩を、文化に。</h4><p>歩いた場所、考えたこと、立ち寄った風呂や食事。短い記録が、次の仲間の行き先になります。</p></div>:<div className="post-list">{data.posts.map(p=><article className="stride-post" key={p.id}><header><span className={'avatar avatar-'+p.role}>{p.name.slice(0,1)}</span><div><strong>{p.name}</strong><small>{p.company} / {p.activity_date}</small></div><b>{p.steps.toLocaleString('ja-JP')}<small> STEPS</small></b></header><h4>{p.title}</h4><p>{p.body}</p>{(p.place_name||p.prefecture)&&<div className="post-place"><MapPin size={14}/>{[p.prefecture,p.place_name].filter(Boolean).join(' / ')}</div>}<footer><button className={p.cheered?'cheered':''} disabled={busy||p.user_id===userId} title={p.user_id===userId?'自分の投稿には送れません':undefined} onClick={()=>action({action:'cheer',id:p.id},p.cheered?'応援を取り消しました。':'NICE STRIDEを送りました。')}><Heart size={16} fill={p.cheered?'currentColor':'none'}/> NICE STRIDE {p.cheers||''}</button><button onClick={()=>share(p)}><Share2 size={16}/> Xでシェア</button>{admin&&<button onClick={()=>action({action:'hide',id:p.id},'投稿を非表示にしました。')}>非表示</button>}</footer></article>)}</div>}
  </section><aside className="session-column"><div className="community-head"><div><span className="eyebrow">SPOTS & SESSIONS</span><h3>次に、行きたい場所</h3></div>{admin&&<Button variant="outline" onClick={()=>setDialog('session')}><Plus size={16}/>企画を作成</Button>}</div>
   <article className="drop-concept"><span>DROP 001 / CONCEPT</span><Shirt size={32}/><h4>WALK<br/>BUILD<br/>RECOVER</h4><p>若手クリエイターやアパレルブランドとつくる、歩くためのユニフォーム。協賛・共同制作パートナー募集中。</p></article>
   {!data.sessions.length?<div className="session-empty"><CalendarDays/><p>ウォーク、温泉・サウナ、食、ポップアップを1つの予定につなげます。開催確定後に運営者が公開します。</p></div>:data.sessions.map(s=>{const K=kinds[s.kind]??kinds.walk,Icon=K.icon;return <article className="session-card" key={s.id}><div className="session-kind"><Icon size={15}/>{K.label}<span>{s.status==='draft'?'下書き':'受付中'}</span></div><h4>{s.title}</h4><p>{s.description}</p><dl><div><dt>HOST</dt><dd>{s.host}</dd></div><div><dt>WHEN</dt><dd>{new Date(s.starts_at).toLocaleString('ja-JP',{timeZone:'Asia/Tokyo',month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}</dd></div><div><dt>WHERE</dt><dd>{s.prefecture} {s.city}</dd></div></dl><div className="session-actions">{s.status==='published'&&<Button variant="outline" disabled={!approved||busy} onClick={()=>action({action:'interest',id:s.id},s.interested?'参加希望を取り消しました。':'「行きたい」に登録しました。')}>{s.interested?'行きたい登録済み':'行きたい'} · {s.interest_count}</Button>}{s.link&&<a href={s.link} target="_blank" rel="noopener noreferrer">詳細 <ArrowUpRight size={14}/></a>}{admin&&s.status==='draft'&&<Button onClick={()=>action({action:'publish_session',id:s.id},'企画を公開しました。')}>公開</Button>}</div></article>})}
  </aside></div>
  <Dialog open={!!dialog} onOpenChange={v=>{if(!v)setDialog('')}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{dialog==='post'?'STRIDE LOGを投稿':dialog==='session'?'新しい企画を作成':'コミュニティへの参加'}</DialogTitle><DialogDescription>{dialog==='post'?'次の誰かが歩きたくなる、短いフィールドノートを残してください。':dialog==='session'?'ウォーク、回復スポット、ポップアップ、アパレル企画を下書きで登録します。':'AI STRIDEは承認制です。'}</DialogDescription></DialogHeader>
   {dialog==='gate'&&<Gate text={authenticated?'運営者によるプロフィール承認後に投稿できます。':'X連携エントリーとプロフィール審査を完了すると投稿できます。'}/>} 
   {dialog==='post'&&<form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await action({action:'post',activity_date:f.get('activity_date'),title:f.get('title'),body:f.get('body'),place_name:f.get('place_name'),prefecture:f.get('prefecture'),steps:Number(f.get('steps'))},'STRIDE LOGを公開しました。'))setDialog('')}}><Label htmlFor="log-date">歩いた日</Label><Input id="log-date" name="activity_date" type="date" max={dateJST()} defaultValue={dateJST()} required/><Label htmlFor="log-steps">その日の歩数</Label><Input id="log-steps" name="steps" type="number" min="0" max="100000" defaultValue="8000" required/><Label htmlFor="log-title">タイトル</Label><Input id="log-title" name="title" maxLength={80} placeholder="昼休みに、次の企画を考える4km" required/><Label htmlFor="log-body">歩いて見つけたこと</Label><Textarea id="log-body" name="body" maxLength={600} placeholder="ルート、考えたこと、食事や回復スポットなど" required/><Label htmlFor="log-place">場所・立ち寄り先（任意）</Label><Input id="log-place" name="place_name" maxLength={100} placeholder="施設名やエリア。現在地の詳細は書かないでください"/><Label htmlFor="log-pref">都道府県（任意）</Label><NativeSelect id="log-pref" name="prefecture" defaultValue=""><NativeSelectOption value="">選択しない</NativeSelectOption>{PREFECTURES.filter(v=>v!=='回答しない').map(v=><NativeSelectOption value={v} key={v}>{v}</NativeSelectOption>)}</NativeSelect><p className="muted">投稿後、Xへのシェアは自分で選べます。自動投稿はしません。</p><Button type="submit" disabled={busy}>公開する</Button></form>}
   {dialog==='session'&&<form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await action({action:'create_session',kind:f.get('kind'),title:f.get('title'),host:f.get('host'),description:f.get('description'),prefecture:f.get('prefecture'),city:f.get('city'),starts_at:f.get('starts_at'),capacity:Number(f.get('capacity')),link:f.get('link')},'企画を下書き保存しました。'))setDialog('')}}><Label htmlFor="session-kind">企画の種類</Label><NativeSelect id="session-kind" name="kind"><NativeSelectOption value="walk">ウォーク</NativeSelectOption><NativeSelectOption value="recovery">温泉・サウナ・回復スポット</NativeSelectOption><NativeSelectOption value="pop_up">ポップアップ</NativeSelectOption><NativeSelectOption value="drop">アパレルドロップ</NativeSelectOption></NativeSelect><Label htmlFor="session-title">企画名</Label><Input id="session-title" name="title" maxLength={100} required/><Label htmlFor="session-host">主催・協賛</Label><Input id="session-host" name="host" maxLength={100} defaultValue="First AI" required/><Label htmlFor="session-desc">内容</Label><Textarea id="session-desc" name="description" maxLength={800} required/><Label htmlFor="session-pref">都道府県</Label><NativeSelect id="session-pref" name="prefecture" required>{PREFECTURES.filter(v=>v!=='回答しない').map(v=><NativeSelectOption value={v} key={v}>{v}</NativeSelectOption>)}</NativeSelect><Label htmlFor="session-city">市区町村・会場</Label><Input id="session-city" name="city" maxLength={100} required/><Label htmlFor="session-start">開催日時</Label><Input id="session-start" name="starts_at" type="datetime-local" required/><Label htmlFor="session-capacity">定員</Label><Input id="session-capacity" name="capacity" type="number" min="1" max="10000" defaultValue="30" required/><Label htmlFor="session-link">外部の詳細URL（任意）</Label><Input id="session-link" name="link" type="url" maxLength={500}/><Button type="submit" disabled={busy}>下書き保存</Button></form>}
  </DialogContent></Dialog>
 </div>
}
function Gate({text}:{text:string}){return <div className="community-empty"><Users/><h4>承認制コミュニティ</h4><p>{text}</p><a className="outline-link" href="/api/x/start" target="_top">Xでエントリー <ArrowUpRight size={15}/></a></div>}
