'use client';
import {useCallback,useEffect,useState} from 'react';
import {Footprints,Trophy,ArrowUpRight,Plus,ChevronLeft,ChevronRight,Activity,Code2,BriefcaseBusiness,Link2,Check,ShieldCheck,Upload,RefreshCw,ExternalLink,Download,Clock3} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Checkbox} from '@/components/ui/checkbox';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
type Row={id:string;name:string;company:string;role:string;total:number;days:number;verified_days:number};
type RecordRow={date:string;steps:number;source:string};
type Member={id:string;name:string;company:string;role:string;profile:string;status:string;created_at:string};
type Data={user:{id:string;name:string}|null;member:Member|null;admin:boolean;rows:Row[];records:RecordRow[];pending:Member[];connection?:{expires_at:number;last_sync:number}|null;hpConfigured:boolean};
const initial:Data={user:null,member:null,admin:false,rows:[],records:[],pending:[],hpConfigured:false};
const dateJST=()=>new Date(Date.now()+9*3600000).toISOString().slice(0,10);
const num=(n:number)=>n.toLocaleString('ja-JP');
const roleName=(r:string)=>r==='engineer'?'AIエンジニア':'AIスタートアップ経営者';
const sourceName=(s:string)=>s==='device'?'機器連携':s==='csv'?'CSV・自己申告':s==='healthplanet-manual'?'HP手入力':'手入力';
const demoRows:Row[]=[{id:'s1',name:'Haru',company:'生成AIプロダクト開発',role:'engineer',total:128460,days:12,verified_days:12},{id:'s2',name:'Sora',company:'AIエージェント事業',role:'founder',total:116230,days:12,verified_days:0},{id:'s3',name:'Rin',company:'機械学習エンジニア',role:'engineer',total:108520,days:11,verified_days:11},{id:'s4',name:'Kai',company:'AIリサーチ',role:'engineer',total:96340,days:12,verified_days:0},{id:'s5',name:'Nao',company:'AI SaaS事業',role:'founder',total:89100,days:10,verified_days:10},{id:'s6',name:'Yuki',company:'LLMアプリ開発',role:'engineer',total:82750,days:11,verified_days:0}];
export default function League(){
 const today=dateJST(),current=today.slice(0,7);
 const [month,setMonth]=useState(current),[role,setRole]=useState('all'),[view,setView]=useState('ranking'),[demo,setDemo]=useState(false),[data,setData]=useState<Data>(initial),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[modal,setModal]=useState(''),[consent,setConsent]=useState(false),[csv,setCsv]=useState<{date:string;steps:number}[]>([]),[csvError,setCsvError]=useState(''),[hpUrl,setHpUrl]=useState('');
 const reload=useCallback(async(signal?:AbortSignal)=>{setLoading(true);try{const r=await fetch('/api/league?month='+month,{signal});const d=await r.json() as Data & {error:string};if(!r.ok)throw new Error(d.error);setData(d);setError('');}catch(e){if(e instanceof Error&&e.name!=='AbortError'){setError(e.message);setData(previous=>({...previous,rows:[],records:[]}));}}finally{if(!signal?.aborted)setLoading(false)}},[month]);
 useEffect(()=>{const c=new AbortController();void reload(c.signal);return()=>c.abort()},[reload]);
 const mutate=async(body:unknown,path='/api/league',message='保存しました。')=>{setBusy(true);setError('');setNotice('');try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error:string;count?:number};if(!r.ok)throw new Error(d.error);await reload();setNotice(message+(typeof d.count==='number'?`（${d.count}日分）`:''));return true}catch(e){setError(e instanceof Error?e.message:'保存できませんでした。');return false}finally{setBusy(false)}};
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'show_monthly_ranking',title:'月間ランキングを表示',description:'選択した月と職種のランキングに画面を切り替えます。記録は変更しません。',inputSchema:{type:'object',properties:{month:{type:'string',pattern:'^\\d{4}-(0[1-9]|1[0-2])$'},role:{type:'string',enum:['all','engineer','founder']}},required:['month','role'],additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:{month:string;role:string})=>{if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(input.month)||input.month>dateJST().slice(0,7)||!['all','engineer','founder'].includes(input.role))throw new Error('年月と職種を確認してください。');const r=await fetch('/api/league?month='+input.month);const d=await r.json() as Data & {error:string};if(!r.ok)throw new Error(d.error);setMonth(input.month);setRole(input.role);setView('ranking');setDemo(false);setData(d);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));return {month:input.month,rows:d.rows.filter((v:Row)=>input.role==='all'||v.role===input.role)}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[]);
 const rows=(demo?demoRows:data.rows).filter(r=>role==='all'||r.role===role);let prev=-1,rank=0;const ranked=rows.map((r,i)=>{if(r.total!==prev)rank=i+1;prev=r.total;return {...r,rank}});
 const all=demo?demoRows:data.rows,mine=data.rows.find(r=>r.id===data.user?.id),total=data.records.reduce((s,r)=>s+r.steps,0),myRank=mine?1+data.rows.filter(r=>r.total>mine.total).length:null;
 const daysInMonth=new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate(),activeMonth=month===current,elapsed=activeMonth?Number(today.slice(8)):daysInMonth,target=daysInMonth*8000,remaining=daysInMonth-Number(today.slice(8))+1;
 function shift(n:number){const d=new Date(month+'-01T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+n);setMonth(d.toISOString().slice(0,7));setDemo(false)}
 function recordAction(){if(!data.user){window.location.href='/signin-with-chatgpt?return_to=/';return}if(data.member?.status==='approved'){setModal('record');setCsv([]);setCsvError('')}else if(!data.member||data.member.status==='rejected')setModal('join');else{setNotice('参加申請を審査中です。承認後に記録できます。')}}
 async function readCsv(file?:File){setCsv([]);setCsvError('');if(!file)return;try{if(file.size>20000)throw new Error('CSVは20KB以内にしてください。');const text=(await file.text()).replace(/^\uFEFF/,'').trim(),lines=text.split(/\r?\n/);if(lines[0].trim()!=='date,steps')throw new Error('先頭行は date,steps にしてください。');const values=lines.slice(1).filter(Boolean).map(line=>{const parts=line.split(',');if(parts.length!==2||!/^\d+$/.test(parts[1].trim()))throw new Error('各行を 日付,整数の歩数 の形式にしてください。');return {date:parts[0].trim(),steps:Number(parts[1])}});if(!values.length||values.length>31||new Set(values.map(r=>r.date)).size!==values.length)throw new Error('重複のない1〜31日分を指定してください。');for(const r of values)if(!/^\d{4}-\d{2}-\d{2}$/.test(r.date)||isNaN(Date.parse(r.date))||new Date(r.date+'T00:00:00Z').toISOString().slice(0,10)!==r.date||!r.date.startsWith(current)||r.date>today||r.steps>100000)throw new Error('当月の今日までの日付と0〜100,000歩を指定してください。');setCsv(values)}catch(e){setCsvError((e as Error).message)}}
 async function hpAuthorize(){setError('');try{const r=await fetch('/api/healthplanet');const d=await r.json() as {error:string;url:string};if(!r.ok)throw new Error(d.error);setHpUrl(d.url)}catch(e){setError((e as Error).message)}}
 function downloadTemplate(){const url=URL.createObjectURL(new Blob(['date,steps\n'+today+',8000\n'],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='ai-stride-template.csv';a.click();URL.revokeObjectURL(url)}
 const bodyError=error&&<p role="alert" className="error-box">{error} <button onClick={()=>reload()} className="text-link">再読み込み</button></p>;
 return <div className="site"><header className="topbar"><a className="brand" href="/"><span className="brand-icon"><Footprints size={22}/></span>AI STRIDE<span className="brand-sub">WALKING LEAGUE</span></a><span className="exclusive">AIエンジニア・AIスタートアップ経営者限定</span>{data.user?<Button variant="outline" onClick={()=>data.member?.status==='approved'?setModal('profile'):setModal('join')}>{data.member?.status==='pending'?'参加申請を審査中':data.member?.status==='approved'?data.member.name:'リーグに参加'} <ArrowUpRight size={16}/></Button>:<a className="outline-link" href="/signin-with-chatgpt?return_to=/" target="_top">ログイン・参加 <ArrowUpRight size={16}/></a>}</header><main className="wrap"><div className="page-heading"><div><p className="eyebrow">THE MONTHLY CHALLENGE</p><h1>コードの先へ、一歩ずつ。</h1><p className="intro">AIをつくる仲間と、毎日の歩数を競おう。</p></div><div className="month-switch"><button aria-label="前の月" onClick={()=>shift(-1)}><ChevronLeft size={18}/></button><label className="sr-only" htmlFor="month">集計月</label><input id="month" type="month" value={month} max={current} onChange={e=>{if(/^\d{4}-(0[1-9]|1[0-2])$/.test(e.target.value)&&e.target.value<=current){setMonth(e.target.value);setDemo(false)}}}/><button aria-label="次の月" disabled={month>=current} onClick={()=>shift(1)}><ChevronRight size={18}/></button></div></div>
 {bodyError}{notice&&<p role="status" className="success-box"><Check size={16}/>{notice}</p>}{data.member?.status==='pending'&&<div className="pending-banner"><Clock3 size={18}/><div><strong>参加申請を受け付けました</strong><p>運営者がプロフィールを確認しています。承認後に記録とランキングへの参加ができます。</p></div><Button variant="outline" onClick={()=>reload()}>承認状況を確認</Button></div>}
 <div className="dashboard"><section className="main-column"><div className="season-card"><div><span className="season-label">MONTHLY LEAGUE / {month.replace('-','.')}</span><h2>今月の一歩が、<br/>次のアイデアになる。</h2><p>{Number(month.slice(5))}.1 — {Number(month.slice(5))}.{daysInMonth} <span>日本時間で集計</span></p></div><div className="season-stat"><Footprints size={32}/><strong>{activeMonth?remaining:daysInMonth}</strong><span>{activeMonth?'DAYS LEFT':'DAYS OF ACTIVITY'}</span></div></div><div className="stats"><div><span>{demo?'サンプルメンバー':'記録メンバー'}</span><strong>{num(all.length)} <small>人</small></strong></div><div><span>{demo?'サンプル累計歩数':'リーグ累計歩数'}</span><strong>{num(all.reduce((s,r)=>s+r.total,0))} <small>歩</small></strong></div><div><span>あなたの順位</span><strong>{demo?'—':myRank??'—'} <small>位</small></strong></div></div>
 <section className="ranking"><div className="section-head"><h2><Trophy size={20}/>{view==='records'?'あなたの記録':view==='admin'?'参加申請の審査':'月間ランキング'}</h2><Button variant="ghost" size="sm" onClick={()=>{setDemo(!demo);setView('ranking')}}>{demo?'実データに戻る':'サンプルを見る'}</Button></div><Tabs value={view} onValueChange={setView}><TabsList variant="line"><TabsTrigger value="ranking">ランキング</TabsTrigger><TabsTrigger value="records">自分の記録</TabsTrigger>{data.admin&&<TabsTrigger value="admin">参加審査 ({data.pending.filter(m=>m.status==='pending').length})</TabsTrigger>}</TabsList></Tabs>
 {view==='ranking'&&<><div className="ranking-toolbar"><Tabs value={role} onValueChange={setRole}><TabsList><TabsTrigger value="all">すべて</TabsTrigger><TabsTrigger value="engineer"><Code2/>エンジニア</TabsTrigger><TabsTrigger value="founder"><BriefcaseBusiness/>経営者</TabsTrigger></TabsList></Tabs><span className="muted">累計歩数順</span></div>{demo&&<div className="sample-banner">表示例です。人物・歩数は架空のサンプルで、実際のランキングには含まれません。</div>}{loading&&!demo?<div className="empty" role="status">ランキングを読み込み中…</div>:ranked.length?<Table><TableHeader><TableRow><TableHead className="rank-col">順位</TableHead><TableHead>メンバー</TableHead><TableHead className="right">累計歩数</TableHead><TableHead className="right days-col">記録日数</TableHead></TableRow></TableHeader><TableBody>{ranked.map(r=><TableRow key={r.id} className={r.id===data.user?.id?'your-row':''}><TableCell className="rank-col"><span className={'rank-medal rank-'+r.rank}>{String(r.rank).padStart(2,'0')}</span></TableCell><TableCell><div className="member-cell"><span className={'avatar avatar-'+r.role}>{r.name.slice(0,1)}</span><div><strong>{r.name}{r.id===data.user?.id&&<span className="you">YOU</span>}</strong><small>{r.company}</small><span className="role-tag">{r.role==='engineer'?'AIエンジニア':'経営者'}</span></div></div></TableCell><TableCell className="right"><strong className="step-number">{num(r.total)}</strong><small className="source-label">{r.verified_days===r.days?'機器連携':r.verified_days>0?'機器・自己申告':'自己申告'}</small></TableCell><TableCell className="right days-col">{r.days}<span className="muted"> 日</span></TableCell></TableRow>)}</TableBody></Table>:<div className="empty"><Footprints size={36}/><h3>今月の最初の一歩を。</h3><p>{error?'記録を読み込めません。再読み込みをお試しください。':'この条件の記録はまだありません。参加承認後、歩数を記録しましょう。'}</p><Button className="mt-5" variant="outline" onClick={recordAction}>参加・記録する <ArrowUpRight size={15}/></Button></div>}<div className="table-note">同じ歩数は同順位。自己申告の記録も集計対象です。</div></>}
 {view==='records'&&<>{data.records.length?<Table><TableHeader><TableRow><TableHead>日付</TableHead><TableHead>登録方法</TableHead><TableHead className="right">歩数</TableHead></TableRow></TableHeader><TableBody>{data.records.map(r=><TableRow key={r.date}><TableCell>{r.date}</TableCell><TableCell><span className="role-tag">{sourceName(r.source)}</span></TableCell><TableCell className="right step-number">{num(r.steps)}</TableCell></TableRow>)}</TableBody></Table>:<div className="empty"><Activity size={32}/><h3>まだ記録がありません</h3><p>1日分の累計歩数を、手入力・CSV・機器連携で登録できます。</p><Button className="mt-5" onClick={recordAction}>歩数を記録</Button></div>}<div className="table-note">登録し直すと、その日の記録を置き換えます。過去月の記録は変更できません。</div></>}
 {view==='admin'&&data.admin&&<div className="review-list">{data.pending.length?data.pending.map(m=><article className="review" key={m.id}><div><strong>{m.name}</strong><span className={'status-tag '+m.status}>{m.status==='pending'?'審査待ち':m.status==='approved'?'承認済み':'却下'}</span><p>{roleName(m.role)} / {m.company}</p><a href={m.profile} target="_blank" rel="noopener noreferrer" className="text-link">公開プロフィールを確認 <ExternalLink size={13}/></a></div><div className="review-actions">{m.status!=='approved'&&<Button disabled={busy} onClick={()=>mutate({action:'review',id:m.id,status:'approved'},undefined,'参加を承認しました。')}>承認</Button>}{m.status!=='rejected'&&<Button disabled={busy} variant="outline" onClick={()=>mutate({action:'review',id:m.id,status:'rejected'},undefined,'参加を却下しました。')}>却下</Button>}</div></article>):<div className="empty"><ShieldCheck size={34}/><h3>申請はまだありません</h3><p>参加申請が届くと、ここで確認・承認できます。</p></div>}</div>}
 </section></section><aside><section className="personal-card"><div className="section-head"><h2>あなたのアクティビティ</h2><Activity size={19}/></div><div className="progress-ring" style={{background:`conic-gradient(#b4db75 ${Math.min(total/target,1)*360}deg,#eef2ec 0deg)`}}><div><span>{Number(month.slice(5))}月の歩数</span><strong>{num(total)}</strong><small>歩</small></div></div><div className="personal-stats"><span>1日平均 <b>{num(Math.round(total/elapsed))} 歩</b></span><span>目安 <b>{num(target)} 歩 / 月</b></span></div><p className="center muted">1日8,000歩を目安に、無理のないペースで。</p><Button className="full" onClick={recordAction}><Plus size={17}/>歩数を記録</Button><Button variant="ghost" className="full csv-button" onClick={()=>{recordAction()}}><Upload size={15}/>CSVからまとめて登録</Button></section><section className="connection-card"><div className="section-head"><Link2 size={22}/><span className="connection-status">{data.connection?'接続済み':'未接続'}</span></div><h3>カロリズムと、つながる。</h3><p>AM-161 → HealthPlanet → AI STRIDE。毎日の歩数をリーグへ。</p><Button variant="outline" className="full" onClick={()=>setModal('connect')}>{data.connection?'連携を管理する':'データ連携について'} <ArrowUpRight size={16}/></Button>{data.connection&&<Button className="full" disabled={busy} onClick={()=>mutate({action:'sync'},'/api/healthplanet','当月の歩数を同期しました。')}><RefreshCw size={15}/>今月の歩数を同期</Button>}<small>{data.hpConfigured?'HealthPlanetから歩数のみを取得します。':'HealthPlanet連携は運営者の初期設定後に利用できます。'}</small></section><button className="rules-link" onClick={()=>setModal('rules')}><ShieldCheck size={16}/>参加条件・ランキングのルール</button></aside></div><footer><span>AI STRIDE © {today.slice(0,4)} <span className="footer-note">独立したコミュニティサービス</span></span><div className="footer-links"><button onClick={()=>setModal('rules')}>ルール・プライバシー</button><button onClick={()=>data.admin?setView('admin'):setModal('admin')}>運営者</button>{data.user&&<a href="/signout-with-chatgpt?return_to=/" target="_top">ログアウト</a>}</div></footer></main>
 <Dialog open={!!modal} onOpenChange={open=>{if(!open){setModal('');setHpUrl('')}}}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>{({join:'リーグへの参加申請',record:'歩数を記録',connect:'HealthPlanetとの連携',rules:'参加条件・ルール',admin:'運営者の初期設定',profile:'参加プロフィール'} as {[k:string]:string})[modal]}</DialogTitle><DialogDescription>{modal==='join'?'AIエンジニア・AIスタートアップ経営者を対象に、運営者がプロフィールを審査します。':modal==='record'?'当月の今日までの累計歩数を登録できます。':modal==='connect'?'AM-161のデータを、まずHealthPlanetアプリに送信してください。':modal==='admin'?'管理者専用の初期設定キーを使い、このアカウントを運営者に登録します。':'AI STRIDEを安心して利用するために。'}</DialogDescription></DialogHeader>{bodyError}
 {modal==='join'&&(data.member?.status==='pending'?<div className="dialog-info"><Clock3/><h3>プロフィールを審査中です</h3><p>運営者の承認をお待ちください。</p></div>:!data.user?<a href="/signin-with-chatgpt?return_to=/" target="_top" className="outline-link">ChatGPTでログインして申請</a>:<form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await mutate({action:'join',name:f.get('name'),company:f.get('company'),role:f.get('role'),profile:f.get('profile'),consent},undefined,'参加申請を受け付けました。')){setModal('');setDemo(false)}}} className="form-stack"><Label htmlFor="name">公開する表示名</Label><Input id="name" name="name" maxLength={60} required placeholder="例：Haru"/><Label htmlFor="company">所属・事業名</Label><Input id="company" name="company" maxLength={100} required placeholder="企業名、または個人の活動名"/><Label htmlFor="role">職種</Label><NativeSelect id="role" name="role" required><NativeSelectOption value="engineer">AIエンジニア</NativeSelectOption><NativeSelectOption value="founder">AIスタートアップ経営者</NativeSelectOption></NativeSelect><Label htmlFor="profile">職歴・事業を確認できる公開URL</Label><Input id="profile" name="profile" type="url" required maxLength={500} placeholder="https://...（会社、GitHub、LinkedInなど）"/><div className="check-row"><Checkbox id="consent" checked={consent} onCheckedChange={v=>setConsent(v===true)}/><label htmlFor="consent">対象職種に該当し、表示名・所属・職種・月間歩数の参加者への公開と、運営者によるプロフィール確認に同意します。</label></div><Button type="submit" className="full" disabled={busy||!consent}>{busy?'送信中…':'参加を申請する'}</Button></form>)}
 {modal==='record'&&<div className="form-stack"><form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await mutate({action:'record',records:[{date:f.get('date'),steps:Number(f.get('steps'))}]},undefined,'歩数を保存しました。')){setMonth(current);setDemo(false);setModal('')}}}><Label htmlFor="date">記録日</Label><Input name="date" id="date" type="date" min={current+'-01'} max={today} defaultValue={today} required/><Label htmlFor="steps">その日の累計歩数</Label><Input name="steps" id="steps" type="number" min="0" max="100000" step="1" placeholder="8000" required/><p className="muted">同じ日付の記録は、今回入力した歩数に置き換わります。</p><Button className="full" type="submit" disabled={busy}>歩数を保存</Button></form><div className="csv-panel"><h3><Upload size={16}/>CSVでまとめて登録</h3><p>date,steps の2列形式。当月分のみ・最大31日。</p><button className="text-link" onClick={downloadTemplate}><Download size={14}/>テンプレートをダウンロード</button><Label htmlFor="csv">CSVファイル</Label><Input id="csv" type="file" accept=".csv,text/csv" onChange={e=>readCsv(e.target.files?.[0])}/>{csvError&&<p role="alert" className="error-box">{csvError}</p>}{csv.length>0&&<><p>{csv.length}日分・合計{num(csv.reduce((s,r)=>s+r.steps,0))}歩を登録します。同日の既存記録を置き換えます。</p><Button disabled={busy} onClick={async()=>{if(await mutate({action:'record',csv:true,records:csv},undefined,'CSVの歩数を保存しました。')){setMonth(current);setDemo(false);setModal('')}}}>この内容で登録</Button></>}</div></div>}
 {modal==='connect'&&<div className="form-stack"><div className="flow"><span>AM-161</span><ArrowUpRight size={16}/><span>HealthPlanet</span><ArrowUpRight size={16}/><span>AI STRIDE</span></div><p>AM-161をHealthPlanetアプリとペアリングし、測定データを転送します。本サイトはHealthPlanetの公開API経由で歩数を読み込みます。</p>{!data.hpConfigured?<div className="dialog-info"><strong>開発者キーの設定待ち</strong><p>運営者がHealthPlanetにアプリを登録し、発行されたキーを設定すると連携できます。手入力・CSVは承認後すぐに使えます。</p></div>:data.member?.status!=='approved'?<p>リーグへの参加が承認されると、連携を開始できます。</p>:<>{!hpUrl?<Button onClick={hpAuthorize}>HealthPlanetの認証を準備する</Button>:<a className="outline-link" href={hpUrl} target="_blank" rel="noopener noreferrer">HealthPlanetで許可する <ExternalLink size={15}/></a>}<form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await mutate({action:'connect',code:f.get('code')},'/api/healthplanet','HealthPlanetに接続しました。同期ボタンで歩数を取得できます。')){setModal('');setHpUrl('')}}}><Label htmlFor="code">許可後に表示される認証コード</Label><Input id="code" name="code" type="password" autoComplete="off" required/><p className="muted">自分のアカウントで許可し、10分以内に入力してください。</p><Button type="submit" disabled={busy}>接続を保存</Button></form>{data.connection&&<Button variant="outline" disabled={busy} onClick={()=>mutate({action:'disconnect'},'/api/healthplanet','連携情報を削除しました。登録済みの歩数は残ります。')}>連携を解除</Button>}</>}<a className="text-link" href="https://www.healthplanet.jp/apis/api.html" target="_blank" rel="noopener noreferrer">HealthPlanet公式API仕様 <ExternalLink size={13}/></a><p className="muted">取得項目は歩数のみ。消費カロリーの公開API連携は2020年6月29日に終了しています。</p></div>}
 {modal==='rules'&&<div className="rules-content"><h3>01 / 対象者と承認</h3><p>AIの開発を行うエンジニア、またはAIを主事業とするスタートアップの経営者が対象です。公開プロフィールを運営者が確認し、承認した方のみ記録できます。</p><h3>02 / 月間ランキング</h3><p>日本時間の毎月1日〜末日の累計歩数で集計。同点は同順位（例：1位、1位、3位）。過去の月は月選択から閲覧できます。記録の追加・変更は当月中のみです。</p><h3>03 / 記録と重複</h3><p>1人1日1件。同日の再登録・同期は上書きです。手入力・CSVは自己申告として表示します。機器連携で同日のデータが複数ある場合は最大の歩数を採用します。API経由でもHealthPlanet上で手入力した値は自己申告です。</p><h3>04 / 公開する情報</h3><p>表示名・所属・職種・月間歩数・記録日数・入力区分をランキングに表示します。審査用プロフィールURLは運営者だけが確認します。連携トークンは暗号化して保存し、連携解除で削除します。体重・体脂肪・消費カロリーは取得しません。</p><h3>05 / 自分のペースで</h3><p>1日8,000歩は画面表示上の目安です。ノルマではありません。運営者は不適切な登録の参加承認を取り消せます。</p><p className="muted">本サイトはタニタの公式サービスではありません。</p><a href="https://www.tanita.co.jp/content/calorism/product/am161/index.html" target="_blank" rel="noopener noreferrer" className="text-link">タニタ AM-161 製品情報 <ExternalLink size={13}/></a></div>}
 {modal==='admin'&&(!data.user?<a className="outline-link" href="/signin-with-chatgpt?return_to=/" target="_top">ログインして初期設定</a>:<form className="form-stack" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(await mutate({action:'bootstrap',key:f.get('key')},undefined,'運営者アカウントを設定しました。')){setModal('');setView('admin')}}}><Label htmlFor="key">運営者用の初期設定キー</Label><Input id="key" name="key" type="password" autoComplete="off" required/><p className="muted">納品した運営ガイドのキーを入力してください。一度登録すると、以降はこのログインアカウントで審査できます。</p><Button type="submit" disabled={busy}>このアカウントを運営者にする</Button></form>)}
 {modal==='profile'&&data.member&&<div className="rules-content"><h3>{data.member.name}</h3><p>{data.member.company}<br/>{roleName(data.member.role)}</p><span className="status-tag approved">運営承認済み</span><p>公開されるのは表示名・所属・職種・月間歩数・記録日数・入力区分です。</p></div>}
 </DialogContent></Dialog></div>
}
